language: python
sudo: false
dist: trusty
cache:
    directories:
        - $HOME/.cache/pipenv
        - $HOME/.cache/pip-tools
        - $HOME/.cache/pip

matrix:
  fast_finish: true

install:
  - "git submodule sync && git submodule update --init --recursive"
  - "python -m pip install --upgrade pip pytest-timeout coverage pipenv"
  - "pipenv install --dev --deploy --system"
script:
    - "pipenv run pytest -ra tests/"

jobs:
  include:
    - stage: test
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - stage: packaging
      python: "3.6"
      install:
        - "python -m pip install --upgrade readme-renderer[md] twine setuptools requests[security]"
      script:
        - "python setup.py sdist"
        - "twine check dist/*"
    - stage: coverage
      python: "3.6"
      install:
        - "pip install --upgrade pip pytest pytest-timeout pytest-cov coverage pipenv"
        - "git submodule sync && git submodule update --init --recursive"
        - "pipenv install --dev --deploy --system"
      script:
        - "pipenv run pytest -n auto --timeout 300 --cov=requirementslib --cov-report=term-missing --cov-report=xml --cov-report=html tests"
